# Generated by Django 4.0.4 on 2022-04-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Создатель заявки')),
                ('content', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('amount', models.IntegerField(verbose_name='Количество товара')),
                ('cur', models.CharField(max_length=50, verbose_name='Валюта')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата конца')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ['start_date', 'price'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created_at', 'name'], 'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='TIN',
            field=models.CharField(max_length=255, verbose_name='Идентификационный номер налогоплательщика'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='remember_token',
            field=models.CharField(max_length=255, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
    ]
