# Generated by Django 4.0.4 on 2022-04-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_category_request_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='cat',
            field=models.BooleanField(default=True, verbose_name='Покупка/ продажа'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
