# Generated by Django 4.0.4 on 2022-04-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_request_cat_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField(verbose_name='Отправитель')),
                ('host', models.IntegerField(verbose_name='Принимающий')),
                ('content', models.CharField(max_length=255, verbose_name='Сообщение')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Сообщению',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Сообщение')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='request',
            name='cur',
            field=models.CharField(max_length=10, verbose_name='Валюта'),
        ),
    ]
